runtime: php
env: flex

runtime_config:
  document_root: public

skip_files:
  - .env

env_variables:
  APP_NAME: bolaodacopa
  APP_ENV: local
  APP_KEY: base64:u5Cit00jkw+g8fdDsgFJZktNCspDqzEgcTrZhEd2eto=
  APP_DEBUG: true

  LOG_CHANNEL: stack
  APP_LOG: daily
  APP_TIMEZONE: UTC

  QUEUE_DRIVER: database

  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_DATABASE: bolaodacopadb
  DB_USERNAME: root
  DB_PASSWORD: Gfr2021!
  DB_SOCKET: /cloudsql/instance_name

  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  SESSION_DRIVER: file
  SESSION_LIFETIME: 120

  GOOGLE_VISION_PROJECT_ID: bolaodacopa-129